apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: "kyverno"
      version: "3.5.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 12h
    
