apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
  namespace: vault
spec:
  secretName: vault-tls-secret
  privateKey:
    rotationPolicy: Always
  commonName: vault.undefinedlab.uk
  dnsNames:
    - vault.undefinedlab.uk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
