# vault-serviceaccount-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vault
  name: vault-service-registration
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-service-registration-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: Role
  name: vault-service-registration
  apiGroup: rbac.authorization.k8s.io
