apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec: 
  interval: 30m
  chart:
    spec:
      chart: "vault"
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace 
  values:
    global:
      enabled: true
      tlsDisable: false
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
          cpu: 250m
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: vault.undefinedlab.uk 
            paths:
              - /
        tls:
          - hosts:
              - vault.undefinedlab.uk 
            secretName: vault-tls-secret
      image:
        repository: "hashicorp/vault"
        tag: "1.16.1"
 
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 500m

      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60

      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: eks-creds
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: eks-creds
          secretKey: AWS_SECRET_ACCESS_KEY
      
      extraVolumes:
        - type: secret
          name: vault-tls-secret
      
      dataStorage:
        enabled: true
      auditStorage:
        enabled: true

      standalone:
        enabled: false
      
      ha:
        enabled: true
        replicas: 5
        raft:
          enabled: true
          setNodeId: true
          config: |
            seal "awskms" {
              region     = "eu-west-3"
              kms_key_id = "arn:aws:kms:eu-west-3:<TON_ACCOUNT_ID>:key/7bfdde74-57d0-4382-88aa-2cef282369cb"
            }
            ui = true
            cluster_name = "vault-integrated-storage"
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
              tls_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "https://vault-0.vault-internal:8200"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-1.vault-internal:8200"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-2.vault-internal:8200"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-3.vault-internal:8200"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
              retry_join {
                leader_api_addr = "https://vault-4.vault-internal:8200"
                leader_client_cert_file = "/vault/userconfig/vault-tls-secret/tls.crt"
                leader_client_key_file = "/vault/userconfig/vault-tls-secret/tls.key"
              }
            } 
      ui:
        enabled: true
        serviceType: "ClusterIP"
        externalPort: 8200