apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7/QY4z1qVUTaIX8AUF9ESaBOu+j+DGyufEn/0A==,iv:DRJY11Jb9NPMHELxbYPF1H2VUTqdtqKFOJTOaOd9bIQ=,tag:o7RNSIbIk+spuM42wP7wUg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cNxHWUUWuuociucy1sZSkT+hylQ3A3p+3UuxNjnPkTjtmqT+qPJhkWVrTpZ8DQpAm8du02c5VjI=,iv:f/zo6w+snQR11DZn0MlT7r3HzjqcF9RQ79VWQFTuqGE=,tag:YDBeX1Q8nmnfPdTiutX0KA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: eks-creds
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d1ZTTTFleElUOGg3UkU1
            U1pzVnRqT2hhdktEcWZFdlU4RGwwVEtMVVRRCkdrNjU0TzZhb1cwR09CbVJ4dWxp
            U0J0d1p6SCt2MUJIcW9LdWNPbnNqUTAKLS0tIEx1T0Q4RXFSaCs3alhIQ1I5MURl
            Q0ZNdHd2NHNBK3o5WDQ5NVBzN205Y1EKKkn8BxqXCHad4CmdzglnB7DSJ+ObcHJA
            06So7xdFacPJWSrMpxBYPcWOtbCjBrTYqP2PhKPpQohD75v7vwEcAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T05:42:39Z"
    mac: ENC[AES256_GCM,data:dDYUmEB++p5NTUSotCYZZhibTl4rTFTPUs9xZB+vuwxapDgBz03JvnwHIvwXuprsC+yOaCHb5XuQ7JD0v+J2Eq8o7jNQUfc/VfVXX7R5dWnG0c5Qr5ieecIQyJ2MTLFT4aR/pSTJCa9WqwLRDi4LQNLcBVWtVchCAzi39Ee/1Sk=,iv:6dY/G3i7OswAvsYIgf5EXXbTVigqeFX5AStXr3K0uFA=,tag:qoW1ORE2TD2gSr2L+Vpbmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
