apiVersion: v1
data:
    token: ENC[AES256_GCM,data:oSam233dtY3+uktb581eEjc617I7fSVkXOrLAEFWAJmy4YwQlanK1qNrMmzFgqdjzELYKzTJoC2Diu+bVQQYwUdk57HNl/bLtR2mD+IGSRSapHiUIa2SGQrfxiYIqr8=,iv:wUV4B14MAsWpQ62xFE/kNhOc0LD4IE3/b3tXI/cYTZU=,tag:fX1KWbpb5l6YAg7Dz+J3Mw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vault-metrics-token
    namespace: vault
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlanFvblpzRWN4bXdBb3lR
            TEp3Z3lhY2ZxczArc2pqTC96KzlHVi8xcTM0CmlObmQ1VEI2dmREVzUvaGNpS0pL
            cXhZa0JnbjZISkZwTGNDYVRGZGNrTHcKLS0tICtyM3l4dEMwb3hJcXpyczZmaUFa
            ZUQ4TU9JWUQwRFh1ODZXU3BuSnZJWDAKIOaVbCXOvsWNeFC+SBjG+TuwXG+82CiO
            6yyupv2fAWAa1ZcKBVOkUx+rhywyCvrrxuNNhX0S3fsSKDs1RWP1lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T21:43:17Z"
    mac: ENC[AES256_GCM,data:gBmXONc+EFL9ITOsW+lzVd8ges4EIQDfyYbvetS5lH6QutZBAjRmFoMHjzuBbyN4IKkRlhKOZk694RetLtRwWp6xY5vZzKmVsIqsB1t8F4pxvNeyyam4mZBOXmZK9xl4W0Hnws70M07YytlfmWBkQcdVsH8mK91X1ymC093Vp/4=,iv:tJ6EWc894WdSeCPczpa2YQqUA56N0OZTepHNdystumw=,tag:aL0+hZV3DH7ycfwH2SjOew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
