apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: "minecraft"
      version: "4.26.3"
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
      interval: 12h
  values:
    eula: "TRUE"
    minecraftServer:
      type: "PAPER"
      version: "1.21"
      memory: "1G"
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: ClusterIP
