apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  chart:
    spec:
      chart: "gitlab"
      version: "9.2.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 12h
  values:
    global:
      hosts:
        domain: undefinedlab.uk
        https: true
      ingress:
        provider: traefik
        enabled: true
        class: gitlab-traefik
        configureCertmanager: true
        tls:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
    certmanager:
      install: false
    certmanager-issuer:
      email: rayane.kadi10@gmail.com
