apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  privateKey:
    rotationPolicy: Always
  commonName: keycloak.undefinedlab.uk
  dnsNames:
    - keycloak.undefinedlab.uk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer