apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 25.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: keycloak
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/keycloak
      tag: 26.3.3-debian-12-r0   
      pullPolicy: IfNotPresent

    global:
      postgresql:
        auth:
          username: bn_keycloak
          password: bn_keycloak
          database: bitnami_keycloak

    auth:
      adminUser: admin
      adminPassword: admin

    # ──────────────────────────────────────────────────────────────
    # Built-in PostgreSQL (simple lab setup). Prefer external CNPG in prod.
    postgresql:
      enabled: false
      # image:
      #   registry: docker.io
      #   repository: bitnamilegacy/postgresql
      #   tag: 17.6.0-debian-12-r0
      # auth:
      #   username: bn_keycloak
      #   password: bn_keycloak
      #   database: bitnami_keycloak

    externalDatabase:
      host: keycloak-db-rw.keycloak.svc.cluster.local
      port: 5432
      user: app          
      database: app      
      existingSecret: keycloak-db-app   
      existingSecretPasswordKey: password  

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: keycloak.undefinedlab.uk
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt 
      extraTls:
        - hosts:
            - keycloak.undefinedlab.uk
          secretName: keycloak-tls-secret
    
    extraEnvVars:
      - name: KC_PRODUCTION
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "true"     
      - name: KC_PROXY
        value: "edge"
      - name: KC_HOSTNAME
        value: "keycloak.undefinedlab.uk"
      - name: KC_HOSTNAME_STRICT
        value: "true"
      - name: VERTX_WORKER_POOL_SIZE
        value: "20"
      - name: VERTX_EVENT_LOOP_POOL_SIZE
        value: "8"
