apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 24.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: keycloak
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: quay.io/keycloak/keycloak
      tag: 25.0.2
      # Global PostgreSQL settings
    global:
      postgresql:
        auth:
          username: bn_keycloak
          password: bn_keycloak
          database: bitnami_keycloak

    # Keycloak Admin User Configuration
    auth:
      adminUser: admin
      adminPassword: admin

    # ──────────────────────────────────────────────────────────────
    # Built-in PostgreSQL (simple lab setup). Prefer external CNPG in prod.
    postgresql:
      enabled: true
      auth:
        username: bn_keycloak
        password: bn_keycloak
        database: bitnami_keycloak

    # ──────────────────────────────────────────────────────────────
    # Service exposure (NodePort for quick testing)
    service:
      type: NodePort
      nodePorts:
        http: 30080

    # ──────────────────────────────────────────────────────────────
    # Extra env for dev/lab access on plain HTTP (NodePort)
    extraEnvVars:
      - name: KC_PRODUCTION
        value: "true"        # run in production mode
      - name: KC_HTTP_ENABLED
        value: "true"        # enable HTTP listener
      - name: KC_PROXY
        value: "edge"        # required when running behind k8s services/ingress
      - name: KC_HOSTNAME_STRICT
        value: "false"
      # Optional (set this if you’ll access via a hostname)
      # - name: KC_HOSTNAME
      #   value: "keycloak.localtest.me"
      # Tuning (optional)
      - name: VERTX_WORKER_POOL_SIZE
        value: "20"
      - name: VERTX_EVENT_LOOP_POOL_SIZE
        value: "8"
