apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail   
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: "promtail"
      version: "6.44.0"
      sourceRef:
        kind: HelmRepository
        name: promtail 
        namespace: monitoring
      interval: 12h
  values:
   config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
          tenant_id: 1
        
