apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: "trivy-operator"
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: trivy-operator
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    trivy:
      ignoreUnfixed: true
    serviceMonitor:
      enabled: true