apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

--- 

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: self-ca
  secretName: self-ca-secret
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
spec:
  ca:
    secretName: self-ca-secret
