apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg
spec: 
  interval: 30m
  chart:
    spec:
      chart: "cloudnative-pg"
      version: "1.18.2"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace 
