apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
  namespace: harbor
spec:
  secretName: harbor-tls-secret
  privateKey:
    rotationPolicy: Always
  commonName: harbor.undefinedlab.uk
  dnsNames:
    - harbor.undefinedlab.uk
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer