apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: "harbor"
      version: "1.17.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  values:
    expose:
      tls:
        certSource: secret
        secret:
          secretName: harbor-tls-secret
      ingress:
        hosts:
          core: harbor.undefinedlab.uk
        annotations:
          kubernetes.io/ingress.class: "traefik"
    externalURL: https://harbor.undefinedlab.uk
