apiVersion: v1
data:
    password: ENC[AES256_GCM,data:R7JJGLS8Lj4=,iv:bykj45h8UmisQC5TMXYMqVWPU5QhapcT+JBjjaq6aKE=,tag:9ljiCob4tePOj2fvyVoa2w==,type:str]
    user: ENC[AES256_GCM,data:7Q3HGI5qk1s=,iv:5wH/fhJUd5JbvPRM0yn5BOrMGDx0s8lOCDjkqdePo9w=,tag:1oB/oELLiLlMGQ82SxP61w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcnlyT0R1eS9mRUVaTW9S
            cXRaa2JrWVpBdXF3eFRmUzFCRUI5ZDhNOURjCkE3cEZhVGlNcnNZdzIrWmQvM09u
            c3k0YXVJRHBSd0c5N2NVeUk3WVZFYUkKLS0tIHVtSU9RdW1TdmhTRmp6dzk2aE92
            cG41cGJnQnBpS3V3R0FwRDdVZ0RCaEUKPjw7zMD/VNBtmDlwfBf0OFf0ZBAG+Xet
            KrLGGv/DFEqjplV3v1JOOreBa6bpOhLKuev2blOdxtlTZ+BtFUnjHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T01:25:42Z"
    mac: ENC[AES256_GCM,data:yq10f/BQlUd0zAQmWMDiKu1NhQCJlctp3hsdKbvcdnrXzTNyD+tb9rnUdAVqZagc6/CypyK7YkWVmlrzVntsXUEW5qPClQJeLDqJp6+QbuACLuUHxNs4/Wi1KscZQjVhcY7aDV1B9VlQ4S3Xi9DKIVH4Y0zTXdgRXLSs2bQ1/dI=,iv:ud2uIPb01/kV0u94QfvV7R1Qb0rj4CaXTgrVutM3VGI=,tag:Q/NsvfAYB61zC+2CaXDwuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
