apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-app
  name: test-app-sa
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: test-app-auth
  namespace: test-app
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: app-role
    serviceAccount: test-app-sa
    audiences:
      - vault

