apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:G70PiAuyRcwkxBcYBJyEjP9ZZzN4XHa7syQNIw+YHGTg0Bv/9V3Ne9ezd5k25Ra4TRpssMhhBqBSHXM/N9FpIl9UyIuw0Y8Yac/lItjDdVzKz1XHlchDJIam8uQ22wmiEh6Y68BL1CluFmb4C6K2AJ9xEBMrCXLi5F8yzSdZxdkCdo5XQ2dDUg+HLmceD4L5GfqQ+WytSpoksNoi3GEiRTTHNG9jxBBeRiQAQ/nmsDnMXlhOkss4ZpQzf98sXNOTLfM1AotNFX8HIsCOVKYvYMgc0XfGmrqJU/hXThDG+/4mdyibEikHESeGNF6dN3ef+7bgaGeWiYRtqRMVU7HRblbbfTPggXdwXQugOoGmxUkwrz1ULqcwYjq89ZJluzn+asDfaxW+Nz0=,iv:JOgFC2+dPV6XnMKf+GO9VyTvKi6armIX2WzKSQAmifQ=,tag:F9pDXEb2dSycWT1Mu/vpdA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: harbor-credentials
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQkJSa0tHWWxVdXRMUUxi
            T2E5bDJsNFVrR0kvalF6VzlKYzZNL2dnckJRCldGdG90TmRNSU4rZEVyTkp4MldH
            cUFoRzhuU0psek9JWGtWTnNka3NoUGMKLS0tIC9DVVJRM3JtTlpLNW1nd1kxYlVW
            WE83YThKUUJmZXNHTk1FMWpNdjYrcFkKtKoJGMYoJ8oAfeDkqcmFZuVQHAl4uTT4
            ya0mi26kX7RcDI4FMzndKPz39hfv9YHFfxpctqMhDugyTC8JyHg20Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T18:48:24Z"
    mac: ENC[AES256_GCM,data:7yzrYQs/m923KPKEjH0h4SBGZw54P5ZexHX/OkxxMI7m5tN2/yWA0rO+j/Yvh/njEroVxb1gbA2GStpOl09OoDlS3F/lFKimDFM1Cp6sL8Es9BqhB2OC6mSdP6a0xG0YMIy5drSTNlf5KTyXHlGcDuLsK/ZsJVrvkEWMlTAAq9I=,iv:RiQ7nsFvTnomN4Dkx7fg69sApzAzj+aJYo7b3Jje5wI=,tag:lUvg2rvlZOizr2kunId2bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
