apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:kvZq9nFBkl0do9S3xXjgCSh2EOsEh5uQZneK9/4f647aTc0t4hiTw5Gu1voSq7Ql0hZYM4y7IKwikW72I3+/oRcF7lOszW5rw+3uCLda1PRcxl8fW64q6WpcDKNroiLUoe8oqzuoUybxJJ6blabkX6HuAuSLKViGIqzvYTWT4C5Om1DIfNGvBS4l5RXKlUluofNM3VCrEqTJgw4DYXBt066zCFmWRA+y3/yb3Rhe8htYpbDbx3pc0wj5YQhIM69LB0GzMKb6+DFPL+kQl914yovPI6yfULiPkLlZA+PFynTzr9kQlIf4EqCoy/ChzPqkaWBx7yZIcopqaapCjHegAe2ptCWLAe7/F55sx/LZQtByrGORVSO4LNvMgWC4ijCo,iv:fpFSAEsKS+7afJm3u8zpFqHuCzffWgwsAwaItZjrrEo=,tag:h/iK8483dQBf0UlLTfoUCg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: harbor-credentials
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWm1uSDhmU2NZQk16Ym5k
            ZXNydG9uM2x5dnJiVENBSjd4WUhXTjNBQXlJCnF5RTdQRGFtRmhiZkMyMkNQbW1l
            Yzk0bUk1RG03VEk5emw3cTZNN2NnSXcKLS0tIGdHZkNPT1YzSHh0aVVNTk5jeDdH
            NGtGdWJQVDQrWm1rcnFZUVY1RlZQd2cKD4BxZ8b3waqoJCGISpG97496ZLrF0SDz
            7I4lu9d+VCima87LF//HeCrfgkC5eZS1K+NVsphzIATj0z+zpNYm2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T19:37:08Z"
    mac: ENC[AES256_GCM,data:H6f9+G/6EFxtLom/QcTbME399g2uiD6egh/RN7YkbcFFnqxMKPTl2LbxtSGwDcJ9II8qD8EgoZJ8G/2Guv5yXg7tGSfVlbypczQ1A/5uMlVgyxhHXzXBmDl3aAsTzi7eUuHNnjrtd+5c+9iqSLVo59dTn8gcQ/2+VrJilGnDhgA=,iv:QZPBjwXHy/01KONS8zCeVEUFNcy3Ylr5VgXub8zuRXE=,tag:3O5nZQ/F8Sh8sBsjIp+cTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
