apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-app-role
  namespace: test-app
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app-rolebinding
  namespace: test-app
subjects:
  - kind: ServiceAccount
    name: test-app-sa
    namespace: test-app
roleRef:
  kind: Role
  name: test-app-role
  apiGroup: rbac.authorization.k8s.io
