apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-app
  namespace: test-app
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/test-app  
      sourceRef:
        kind: GitRepository
        name: homelab-cluster
        namespace: flux-system
      interval: 12h
  values:
