apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-cluster
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/rayanoss/homelab-cluster
  ref:
    branch: main
