apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: test-app-vs
  namespace: test-app
spec:
  type: kv-v2
  mount: kvv2
  path: testapp/config
  destination:
    name: secretkv
    create: true
  refreshAfter: 30s
  vaultAuthRef: test-app-auth
  rolloutRestartTargets:
  - kind: Deployment
    name: test-app


---
  
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: test-app-vd
  namespace: test-app
spec:
  vaultAuthRef: test-app-auth
  mount: app-postgres
  path: creds/app-role
  destination:
    create: true
    name: postgres
  rolloutRestartTargets:
  - kind: Deployment
    name: test-app

