apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

secretGenerator:
  - name: runner-token
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=values.yaml
      
configurations:
  - kustomizeconfig.yaml