apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: "gitlab-runner"
      version: "9.2.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: gitlab-runner
      interval: 12h
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
    serviceAccount:
      create: true
      name: gitlab-runner
  valuesFrom:
    - kind: Secret
      name: runner-token
