apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: "gitlab-runner"
      version: "0.79.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: gitlab-runner
      interval: 12h
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
    serviceAccount:
      create: true
      name: gitlab-runner
    runners:
    config: |
      [[runners]]
        executor = "kubernetes"
        [runners.kubernetes]
          privileged = true
          [[runners.kubernetes.services]]
            name = "docker:24.0.7-dind"
            command = ["--host=tcp://0.0.0.0:2375", "--tls=false"]
  valuesFrom:
    - kind: Secret
      name: runner-token
