apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: test-app-db-monitor
  namespace: monitoring 
spec:
  namespaceSelector:
    matchNames:
      - test-app
  selector:
    matchLabels:
      cnpg.io/cluster: test-app-db
  podMetricsEndpoints:
    - port: metrics
