apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy
spec:
  interval: 30m
  chart:
    spec:
      chart: "trivy"
      version: "0.19.1"
      sourceRef:
        kind: HelmRepository
        name: trivy
        namespace: trivy
      interval: 12h
  values:
    trivy:
      ignoreUnfixed: true
    serviceMonitor:
      enabled: true